name: Black code style check

on: [push]

jobs:
  black:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Install apt dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y -qq python3-pip
    - name: Add the bin directory pip uses for executables on PATH
      run: |
        echo "::add-path::/home/runner/.local/bin"
    - name: Install pip dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install black
    - name: Check code style with Black 
      run: |
        black --check --diff .
