name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - name: Install GRASS GIS and other dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y -qq grass grass-dev grass-doc wget
    - name: Fix GRASS GIS installation for g.extension
      run: |
        wget https://grass.osgeo.org/grass78/manuals/grass_logo.png
        wget https://grass.osgeo.org/grass78/manuals/grassdocs.css
        sudo mv grass_logo.png /usr/lib/grass78/docs/html/grass_logo.png
        sudo mv grassdocs.css /usr/lib/grass78/docs/html/grassdocs.css
    - name: Create a temporary location
      run: |
        grass -c EPSG:4326 ~/grasstmploc -e
    - name: Chanage shebang to Python3
      run: |
        sed -i s/python/python3/g r.example.plus.py
        sed -i s/python/python3/g testsuite/test_r_example_plus.py
    - name: Install the module
      run: |
        grass ~/grasstmploc/PERMANENT --exec g.extension extension=${{ github.event.repository.name }} url=. --verbose
    - name: Cache data for testing
      id: cache-nc_spm_08_grass7
      uses: actions/cache@v1
      with:
        path: nc_spm_08_grass7
        key: ${{ runner.os }}-nc_spm_08_grass7
    - name: Get sample data for testing (NC SPM sample location)
      if: steps.cache-nc_spm_08_grass7.outputs.cache-hit != 'true'
      run: |
        grass ~/grasstmploc/PERMANENT --exec g.extension g.download.location --verbose
        grass ~/grasstmploc/PERMANENT --exec g.download.location url=https://grass.osgeo.org/sampledata/north_carolina/nc_spm_08_grass7.tar.gz --verbose
    - name: Run test (manually specified files)
      run: |
        cd testsuite/
        grass -c ~/nc_spm_08_grass7/test --exec python3 ./test_r_example_plus.py
        rm -rf ~/nc_spm_08_grass7/test
