name: Deploy online documentation

on:
  push:
    branches:
    - master

jobs:
  build-deploy:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - name: Install GRASS GIS and other dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y -qq grass grass-dev grass-doc wget
    - name: Fix GRASS GIS installation for g.extension
      run: |
        wget https://grass.osgeo.org/grass78/manuals/grass_logo.png
        wget https://grass.osgeo.org/grass78/manuals/grassdocs.css
        sudo mv grass_logo.png /usr/lib/grass78/docs/html/grass_logo.png
        sudo mv grassdocs.css /usr/lib/grass78/docs/html/grassdocs.css
    - name: Create a temporary location
      run: |
        grass -c EPSG:4326 ~/grasstmploc -e
    - name: Chanage shebang to Python3
      run: |
        sed -i s/python/python3/g r.example.plus.py
    - name: Install the module to directory called build
      run: |
        grass ~/grasstmploc/PERMANENT --exec g.extension extension=${{ github.event.repository.name }} url=. prefix=build --verbose
    - name: Copy the page as index.html
      run: |
        cp build/docs/html/${{ github.event.repository.name }}.html build/docs/html/index.html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./build/docs/html
